--BÝR MAÐAZANIN GÜN BAZLI SATIÞ RAKAMLARI
SELECT BRANCH SUBE, DATE_ TERÝH, SUM(LINENET) TOPLAMSATIS, COUNT(*) SATIRSAYISI
FROM SALES 
--WHERE BRANCH = 'ANKARA SUBESÝ' --and DATE_ = '2017-01-05'
GROUP BY BRANCH, DATE_
ORDER BY BRANCH, DATE_ 