--En çok satýþ yapýlan urun kategorileri
SELECT
I.CATEGORY1, I.CATEGORY2, I.CATEGORY3, SUM(OD.TOTALPRICE) AS Toplam
FROM ITEM I
INNER JOIN ORDERDETAIL OD ON OD.ITEMID = I.ID
INNER JOIN ORDER_ O ON O.ID = OD.ORDERID
GROUP BY I.CATEGORY1, I.CATEGORY2, I.CATEGORY3
ORDER BY SUM(OD.TOTALPRICE) DESC