--En cok satýþ yapýlan müþteriler
SELECT 
U.USERNAME_, U.NAMESURNAME, SUM(BD.TOTAL) AS Toplam
FROM USER_ U
INNER JOIN BASKET B ON B.USERID = U.ID
INNER JOIN BASKETDETAIL BD ON BD.BASKETID = B.ID
GROUP BY U.USERNAME_, U.NAMESURNAME
ORDER BY SUM(BD.TOTAL) DESC