SELECT
U.NAMESURNAME AS AdSoyad, B.CREATEDDATE AS OlusturmaTarihi,
BD.AMOUNT AS Miktar, BD.PRICE AS Fiyat, BD.TOTAL AS Toplam,
I.ITEMCODE AS UrunCodu, I.ITEMNAME AS UrunAdý, I.CATEGORY1, I.CATEGORY2, I.CATEGORY3,
A.ADDRESSTEXT as Adres, C.CITY AS Sehir, T.TOWN AS Ilce, D.DISTRICT AS Mahalle,
INV.INVOICENO AS FaturaNo, INV.CARGOFICHENO AS KargoNumarasý, INV.DATE_ AS FaturaKesimTarihi
FROM USER_ U
INNER JOIN BASKET B ON B.USERID = U.ID
INNER JOIN BASKETDETAIL BD ON BD.BASKETID = B.ID
INNER JOIN ITEM I ON I.ID = BD.ID
INNER JOIN ORDER_ O ON O.BASKETID = B.ID
INNER JOIN ADDRES A ON A.ID = O.ADDRESSID
INNER JOIN CITY C ON C.ID = A.CITYID
INNER JOIN TOWN T ON T.ID = A.TOWNID
INNER JOIN DISTRICT D ON D.ID = A.DISTRICTID
INNER JOIN INVOICE INV ON INV.ORDERID = O.ID
