--KULLANICILARIN ADRES SAYILARI VE FARKLI ADRES SAYILARI
SELECT 
U.USERNAME_, U.NAMESURNAME, U.EMAIL, U.TELNR1, U.TELNR2,
COUNT(A.ID) AS ADRESSAYISI, COUNT(DISTINCT C.CITY)
FROM USER_ U
JOIN ADDRES A ON U.ID = A.USERID
JOIN CITY C ON C.ID = A.CITYID
JOIN TOWN T ON T.ID = A.TOWNID
JOIN DISTRICT D ON D.ID = A.DISTRICTID
--WHERE U.ID = 1
GROUP BY U.USERNAME_, U.NAMESURNAME, U.EMAIL, U.TELNR1, U.TELNR2
ORDER BY COUNT(A.ID) DESC
--HAVING COUNT(A.ID) = 2