--maðazalarýmýzýn müþteri sayýLarýný saydýrmak
select BRANCH , COUNT(DISTINCT CLIENTNAME)
FROM SALES
WHERE BRANCH IS NOT NULL
GROUP BY BRANCH

--TÜM MÜÞTERÝ SAYISI
SELECT COUNT(DISTINCT CLIENTNAME)
FROM SALES 


