--ASCII
SELECT ASCII('Ç')

--CHAR
SELECT CHAR(199)

--SUBSTRING
SELECT SUBSTRING('BEKÝR GERÝÞ SQL ÇALIÞIYOR', 5, 4)

--CHARINDEX
SELECT CHARINDEX('eK', 'bEKÝR GERÝÞ' ,1)

--CONCAT
SELECT CONCAT('BEKÝR', ' ', 'GERÝÞ')
SELECT CONCAT_WS(' ', 'BEKÝR', 'GERÝÞ')
SELECT 
CONCAT_WS(' ', USERNAME_, PASSWORD_, NAMESURNAME)
FROM USER_

--FORMAT
SELECT FORMAT(GETDATE(), 'd', 'en-us')
SELECT FORMAT(GETDATE(), 'd', 'en-us')
SELECT FORMAT(GETDATE(), 'D', 'de-de')

--LEFT. RIGHT VE LEN
SELECT LEFT('BEKÝR GERÝÞ' , 5)
SELECT RIGHT('BEKÝR GERÝÞ' , 5)
SELECT LEN('BEKÝR GERÝÞ')
SELECT LEFT('BEKÝR GERÝÞ' , CHARINDEX(' ', 'BEKÝR GERÝÞ')),
RIGHT('BEKÝR GERÝÞ' , LEN('BEKÝR GERÝÞ') - CHARINDEX(' ', 'BEKÝR GERÝÞ'))

--TRIM, LTRIM VE RTRIM
SELECT TRIM('   Ý K    K   BEKÝR GERÝÞ    ')
SELECT LTRIM('   Ý K    K   BEKÝR GERÝÞ    ')
SELECT RTRIM(' Ý K    K   BEKÝR GERÝÞ ')

--LOWER, UPPER, REVERSE, REPLICATE
SELECT LOWER('Bekir')
SELECT UPPER('Bekir')
SELECT REVERSE('Bekir')
SELECT REPLICATE('Bekir', 2)

--REPLACE
SELECT REPLACE('BEKÝR GERÝÞ', 'B', '555')

