--ürün kategorþilerine göre satýþ rakamlarý

select CATEGORY_NAME1, BRAND, SUM(LINENET) AS TOPLAMSATIS
FROM SALES
WHERE CATEGORY_NAME1 IS NOT NULL AND CATEGORY_NAME1 = 'GIDA'
GROUP BY CATEGORY_NAME1, BRAND
ORDER BY SUM(LINENET) DESC